include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    inference_failure_on_untyped_parameter: ignore
    inference_failure_on_function_return_type: ignore
    avoid_annotating_with_dynamic: ignore
    avoid_dynamic_calls: ignore
    avoid_catches_without_on_clauses: ignore
    avoid_returning_this: ignore
    depend_on_referenced_packages: ignore
    file_names: error

linter:
  rules:
    
    void_checks: false
    overridden_fields: false
    use_setters_to_change_properties: false
    avoid_shadowing_type_parameters: false
    avoid_annotating_with_dynamic: true
    avoid_dynamic_calls: true
    use_build_context_synchronously: false
    public_member_api_docs: false
    type_annotate_public_apis: false
    lines_longer_than_80_chars: false
    document_ignores: false

