include: package:very_good_analysis/analysis_options.yaml


linter:
  rules:
    file_names: false
    avoid_annotating_with_dynamic: true
    avoid_dynamic_calls: true
    use_build_context_synchronously: false
    public_member_api_docs: false
    type_annotate_public_apis: false
    lines_longer_than_80_chars: false
    document_ignores: false

